#!/bin/sh
yum --disablerepo=* \
    --enablerepo=BaseOS \
    --enablerepo=extras \
    --enablerepo=centosplus \
    --enablerepo=AppStream \
    --enablerepo=PowerTools \
    --enablerepo=Devel \
    --enablerepo=cr \
    "$@"
